# Generated by Django 3.2.1 on 2021-05-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='media', verbose_name='Картинка')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateField(verbose_name='Дата')),
                ('author_name', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
