# Generated by Django 3.2.1 on 2021-05-06 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='post',
            new_name='news',
        ),
    ]
