# Generated by Django 3.2.1 on 2021-05-06 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_post_images_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='news',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='news.news', verbose_name='Для новости'),
        ),
    ]
