# Generated by Django 3.2.1 on 2021-05-10 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='media', verbose_name='Картинка')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateField(verbose_name='Дата')),
                ('author_name', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Обучение',
                'verbose_name_plural': 'Обучения',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media', verbose_name='Фото')),
                ('study', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='study.study', verbose_name='Для обучения')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('author_mail', models.CharField(max_length=200, verbose_name='Почта автора')),
                ('site', models.CharField(blank=True, max_length=100, verbose_name='Сайт автора')),
                ('comment', models.TextField(verbose_name='Коментарий')),
                ('post', models.BooleanField(verbose_name='Опубликовать?')),
                ('study', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='study.study', verbose_name='Для обучения')),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Коментарии',
            },
        ),
    ]
