# Generated by Django 3.2.1 on 2021-05-06 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название категории')),
                ('slug', models.CharField(blank=True, max_length=40)),
                ('image', models.ImageField(default='', upload_to='media')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название подкатегории')),
                ('slug', models.CharField(blank=True, max_length=40)),
                ('image', models.ImageField(default='', upload_to='media')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.categories')),
            ],
            options={
                'verbose_name': 'Подкатегорию',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название товара')),
                ('slug', models.CharField(blank=True, max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена товара')),
                ('image', models.ImageField(upload_to='media', verbose_name='Фотография товара')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('article', models.CharField(max_length=20, verbose_name='Артикул')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcategories')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
